# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Build

on:
  workflow_dispatch:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  platformio:
    name: "pio:${{ matrix.env }}:${{ matrix.board }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - env: ci-arduino-2
            board: esp32dev
          - env: ci-arduino-2
            board: esp32-s2-saola-1
          - env: ci-arduino-2
            board: esp32-s3-devkitc-1
          - env: ci-arduino-2
            board: esp32-c3-devkitc-02

          - env: ci-arduino-3
            board: esp32dev
          - env: ci-arduino-3
            board: esp32-s2-saola-1
          - env: ci-arduino-3
            board: esp32-s3-devkitc-1
          - env: ci-arduino-3
            board: esp32-c3-devkitc-02
          - env: ci-arduino-3
            board: esp32-c6-devkitc-1

          # - env: ci-arduino-rc
          #   board: esp32dev
          # - env: ci-arduino-rc
          #   board: esp32-s2-saola-1
          # - env: ci-arduino-rc
          #   board: esp32-s3-devkitc-1
          # - env: ci-arduino-rc
          #   board: esp32-c3-devkitc-02
          # - env: ci-arduino-rc
          #   board: esp32-c6-devkitc-1

          - env: ci-esp8266
            board: huzzah
          - env: ci-esp8266
            board: d1_mini

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pio
          path: |
            ~/.cache/pip
            ~/.platformio

      - name: Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Build
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          pip install --upgrade intelhex

      - run: PLATFORMIO_SRC_DIR=examples/Logging PIO_BOARD=${{ matrix.board }} pio run -e ${{ matrix.env }}
      - run: PLATFORMIO_SRC_DIR=examples/HighPerf PIO_BOARD=${{ matrix.board }} pio run -e ${{ matrix.env }}
